### ISSUE TITLE
{"version":"1.0.1","github_sha":"4de0786162334e7e9acd41c1def52e8aae1e14d4

### ISSUE THREAD

**Issue by melyalex** [melyalex/misscrypto#1]
[
  {
    "type": "user",
    "url": "https://github.com/melyalex",
    "avatar_url": "https://avatars0.githubusercontent.com/u/70414363?v=4",
    "login": "melyalex",
    "name": "Melissa Lunardi",
    "bio": "",
    "company": null,
    "website": "http://linkedin.com/in/melissa-lunardi-b9b091167",
    "location": "Italy",
    "emails": [
      {
        "address": "e.melissa.lunardi@gmail.com",
        "primary": true,
        "verified": true
      },
      {
        "address": "70414363+melyalex@users.noreply.github.com",
        "primary": false,
        "verified": true
      }
    ],
    "billing_plan": {
      "name": "free",
      "space": 976562499,
      "private_repos": 10000
    },
    "created_at": "2020-08-28T22:18:07Z"
  }
]

**Comment by Ghostnogo** [comment]
K
